# Generated by Django 3.2.7 on 2021-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211011_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='times_password_changed',
            field=models.IntegerField(default=0),
        ),
    ]
