# Generated by Django 3.2.7 on 2021-10-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_provider',
        ),
    ]
