# Generated by Django 3.2.7 on 2021-10-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211020_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'users'},
        ),
    ]
